### ISSUE TITLE
Rainbow gem, metal sonic and change to night

### ISSUE THREAD

**Issue by jcamarinha700** [lost-legacy-team/LoS-Mod_Files_X#12]
Hello, a month ago I discovered your legacy of solaris project and I loved your mod, I have seen that you have restored a lot of deleted content and there are precisely 3 things that I have seen on the wiki that were removed in the final version and I would love to know if you can put in your mod, it's more like a doubt if it is possible to implement it (as I discovered your project not long ago, I don't know if you are already working on it)

First: I would like to know if it is possible to activate the rainbow gems that were used to transform Sonic, Shadow and Silver into their super forms? I have seen several mods that try to enable it but I understand that they are not very functional and that is why I would like to know if they can make them functional?

second: could you add being able to play as metal sonic? on the wiki it says that deleted text was found that said that metal sonic could have been intended as a playable character, I know there is a mod that replaces sonic with metal sonic, so I would like to know if instead of replacing it it is added as a new character like they did with mephilis? you could use some super sonic animations and give him his own levels like with mephilis
Third and last: I have seen that originally the game could go from day to sunset and night, I have even seen a recreation of that demo for PC, could it be enabled for that to happen in the game?
sorry for my bad english i use translator

**Comment by Knuxfan24** [comment]
Rainbow Gem requires a lot of custom code.
Metal literally only has a few text strings and a reference to a non existent particle bank.
We haven't found a good way to emulate the time cycle (was probably staged as a tech demo rather than something in the actual game honestly).
