### ISSUE TITLE
problems installing the latest version of legacy of solaris in a game without mods

### ISSUE THREAD

**Issue by jcamarinha700** [lost-legacy-team/LoS-Mod_Files_X#14]
good, I was installing the legacy of solaris in its latest version (in a game extracted without mods) and I get these errors when I finish installing, the game seems to grab well, but I don't know if this will generate errors later? 
![image](https://user-images.githubusercontent.com/66115897/168142463-fa9851e6-495a-4ab7-8288-8c37d4c1dda1.png)

**Comment by Knuxfan24** [comment]
Go to the updates tab in the Mod Manager and select "Fetch Latest Patches"

**Comment by jcamarinha700** [comment]
> Go to the updates tab in the Mod Manager and select "Fetch Latest Patches"

I get this when trying to update
![Captura](https://user-images.githubusercontent.com/66115897/168154129-f28e62d2-31e3-4efb-98d6-fcb2b3331d71.PNG)

**Comment by jcamarinha700** [comment]
> Go to the updates tab in the Mod Manager and select "Fetch Latest Patches"

thank you very much, that was it, problem solved, greetings from Venezuela
