### ISSUE TITLE
Can't play on my Modded Xbox 360

### ISSUE THREAD

**Issue by AquaSurge101** [lost-legacy-team/LoS-Mod_Files_X#2]
I did everything correctly as stated in the instructions but for some reason the game keeps crashing after the first two cut scenes whenever I try to start Sonic's story. I could really use some help, I also noticed some of the textures missing in the cutscenes like for example, when Eggman caught Elise and she gave sonic the chaos emerald Eggman's battleship was invisible. I'm not sure what the issue is.

**Comment by HyperPolygon64** [comment]
Merge 'object.arc' like listed in the instructions.

**Comment by AquaSurge101** [comment]
I did, I must not have done it correctly

**Comment by AquaSurge101** [comment]
I'll try it again but thanks

**Comment by AquaSurge101** [comment]
Now for some reason when I try to merge the files, it keeps coming up with errors saying access to the path denied. I tried running the program as an administrator but it still keeps saying the same thing. I'm not sure what to do.

**Comment by AquaSurge101** [comment]
Nevermind I got it working now, I had the object.arc file set to "read only"...
