### ISSUE TITLE
Mod Manager Error

### ISSUE THREAD

**Issue by ZuranaSuki** [lost-legacy-team/LoS-Mod_Files_X#3]
The mod manager says it has completed installing the mods but some were skipped 
![image](https://user-images.githubusercontent.com/16857139/70184170-5047dd00-16b5-11ea-8967-53fe7a66390f.png)

**Comment by HyperPolygon64** [comment]
There's two reasons this happens:
1. You're installing the Xbox 360 version of Legacy of Solaris (from this repository) on the PlayStation 3 version of the game.
2. You don't have your Game Directory set properly in Sonic '06 Mod Manager.

**Comment by ZuranaSuki** [comment]
im using the 360 version of the game and i have the directory point to the root here
![image](https://user-images.githubusercontent.com/16857139/70184400-c4828080-16b5-11ea-9e5f-f9ea16dd5160.png)

**Comment by HyperPolygon64** [comment]
I notice 'ZLIB123.TXT' is missing. Did you extract your ISO with Sonic '06 Toolkit?

**Comment by ZuranaSuki** [comment]
yes i did

**Comment by HyperPolygon64** [comment]
The extractor should tell you once it's done. Worth nothing that when the Toolkit says 'Ready.' - that doesn't imply it's finished. Click on that text to open the Session Log and wait for the proper message to appear when extracting. =P

It should say 'Image.iso has extracted successfully...'

**Comment by ZuranaSuki** [comment]
ok yea that was my problem i closed out before it finished only error i get now is this
![image](https://user-images.githubusercontent.com/16857139/70185825-8f2b6200-16b8-11ea-92d4-fd871edf36bf.png)

**Comment by HyperPolygon64** [comment]
If you have any other mods enabled, set them to a higher priority than Legacy of Solaris.

**Comment by ZuranaSuki** [comment]
this happens instead now
![image](https://user-images.githubusercontent.com/16857139/70186679-6e640c00-16ba-11ea-867f-cddc91ddde3f.png)

**Comment by HyperPolygon64** [comment]
That mod is ancient and shouldn't be used - if you're intending to use Vulkan, enable the Destructive renderer in the Patches tab. I'd recommend using [this build of Xenia](https://ci.appveyor.com/api/buildjobs/1xt1fwpb74vvo317/artifacts/xenia-master.zip) instead and setting the Graphics API in the Emulator tab to DirectX 12.

**Comment by ZuranaSuki** [comment]
ah ok everything is working now thanks for the help! ^_^
