### ISSUE TITLE
Multiplayer

### ISSUE THREAD

**Issue by TheTreeChameleon** [lost-legacy-team/LoS-Mod_Files_X#4]
I have a little suggestion. Would it be a possibility to add the amigo characters on the select screen for the multiplayer? My brother and I have a blast playing multiplayer in vanilla '06, so I was just thinking about it. I completely understand if you think it will be too much work to implement. I was looking high and low for the files to alter myself.

**Comment by HyperPolygon64** [comment]
Not possible, at the moment. The only reason amigo characters are possible in single player is because the DLC pretty much handed us the scripts we needed to achieve it.
