### ISSUE TITLE
Shadow Mach Sections

### ISSUE THREAD

**Issue by G-rain87** [lost-legacy-team/LoS-Mod_Files_X#7]
... Is bugged, I think. The "Extra" stage of Wave Ocean has him doing Sonic's Mach section, but so painfully slow that he can't make it off the last ramp. Also, for some reason, I can't reliably clear the Radical Train stage because the motorcycle (either, doesn't matter) can't seem to do damage to the train's last section regardless of where it's hitting.

**Comment by JotaroPowered** [comment]
I haven't had any problems with either of those things.

**Comment by JotaroPowered** [comment]
I will test it out now but if nothing is wrong, I'm sorry this seems more like a problem on your end.

**Comment by JotaroPowered** [comment]
I just tested Shadow's Extra Wave Ocean and it was fully beatable, did you perhaps mean the Super Hard Mode layout?

**Comment by JotaroPowered** [comment]
Just tested out Shadow's Radical Train 
![image](https://user-images.githubusercontent.com/44914795/101852074-d5689c00-3b2a-11eb-855a-060a953f5d68.png) It was beatable with no problems.

**Comment by G-rain87** [comment]
Strange issues to have solely here, then. Maybe something just went wrong at the startup that one time, I dunno. I am curious: Why are we being forced to use a third-party app to install the mod? I remember when it was neatly packaged by itself.

**Comment by Knuxfan24** [comment]
"Why are we being forced to use a third-party app to install the mod?"
LoS, like a lot of '06 Mods, are using the Mod Manager's Merge Mod functionality to both reduce the filesize of the mod & remove redundancy, as only the files in the archives that are changed are required to be provided, the Manager handled merging them with the base game. Patches are used too, which is another Mod Manager feature.

**Comment by JotaroPowered** [comment]
I would recommend you joining the server so I can better address your questions. I am closing this here.
